on: push

  #schedule:
  #- cron:  '5 * * * *'
  #- cron:  '0 1-13 * * 1-5'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir log
          date > log/generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add log/generated.txt
          git commit -m "generated"
          git push
